import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :controller, Controller.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  # Hot reloading purges old module versions on the next request, which kills
  # any task running inside them (an axis scan, a long hold). A field session
  # must not lose a run to an edit: reload only when asked for.
  code_reloader: System.get_env("OBS_RELOAD") == "1",
  debug_errors: true,
  secret_key_base: "C/JehPi8qBCmyw8RFr8aKkeUqVpE9PSgx1QvDGQv+A8i0m8QbtzrYqufw/p1G1cJ",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :controller, Controller.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/controller/router\.ex$"E,
      ~r"lib/controller/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :controller, dev_routes: true

# No cable plugged in? Run a simulated EQ6-R so the rest of the stack still works.
config :mount, simulate_when_empty: true

# This Mac keeps to itself unless told to join the observatory cluster:
#
#     OBSERVATORY_CLUSTER=1 mix phx.server
#
# With it, this Mac is a node: a box's mount on the network can be connected
# from the Devices page and driven from any page here, its frames are copied
# here and its plates solved here. A box that was connected before
# (~/.observatory/boxes.txt) is joined again by itself, and other Macs started
# the same way are found by LAN gossip. The cookie is the cluster's shared
# secret; a box uses the same (firmware OBSERVATORY_COOKIE).
#
# Without it there is no distribution, no gossip and no looking for boxes. It
# used to be always on: a dev server started for something else joined the
# telescope box in use that night (it was in boxes.txt), and its simulated
# camera showed on the box as live frames of stars.
if System.get_env("OBSERVATORY_CLUSTER") == "1" do
  config :telescope,
    distribution: [name: "observatory", cookie: String.to_atom(System.get_env("OBSERVATORY_COOKIE", "observatory"))],
    boxes_file: Path.join(System.user_home!(), ".observatory/boxes.txt")
else
  # :none, not []: an empty list merges into config.exs's [lan: ...] and changes nothing
  config :libcluster, topologies: :none
end

# No telescope camera plugged into the Mac: use the simulated one on the
# simulated mount (Controller.ScopeCamera.Sim)
config :controller, :scope_camera, sim: true

# The Mac is the mothership: it copies kept frames off every box (Controller.Frames)
config :controller, :frames, pull: true

# No Sony on this Mac: a simulated a6000 (Camera.Transport.Sim) so the Stills Camera page works
config :camera, simulate: true
