"""Step 11: the recipe: every frame, every parameter, every check, written beside the pictures."""
import json, os, sys, glob, platform, datetime
import numpy as np, cv2, tifffile, rawpy, scipy, PIL
from common import *
from final import *
DRY = len(sys.argv) > 1 and sys.argv[1] == 'dry'
DEST = W('out_dry') if DRY else OUT
L = lambda n: json.load(open(W(n)))
s1l = L('step1.json'); s1 = {f['stamp']: f for f in s1l['frames']}; s2 = L('step2.json'); s2f = {f['stamp']: f for f in s2['frames']}
s3 = {r['stamp']: r for r in L('step3_stars.json')}; T4 = L('step4_transforms.json'); tr = {o['stamp']: o for o in T4['transforms']}
Q = L('step5_quality.json'); q = {o['stamp']: o for o in Q['quality']}; sel = L('step7_select.json'); useby = {u['stamp']: u for u in sel['used']}; rejby = {r['stamp']: r for r in sel['rejected']}
vig = L('vignette.json'); dust = L('dust.json'); dustmap = L('dustmap.json'); chk = L('check_flat.json'); star = L('starcolour.json'); flat2d = L('flat2d.json'); sharp = L('sharpen_report.json'); vfit = L('vig_fit.json')
s8 = {v: L('step8_%s.json' % v) for v in 'ABC'}; s10 = L('step10.json'); N = s10['numbers']
USED = [u['stamp'] for u in sel['used']]; n_used = len(USED); x0, y0, x1, y1 = s10['rect']
wsum = sum(u['weight'] for u in sel['used'])
# noise model of one colour plane, from the frames' own blocks (step 3 fits the mean of the two green planes: twice the variance for one plane)
a = float(np.median([s3[s]['noise_model']['a'] for s in USED])) * 2; b = float(np.median([s3[s]['noise_model']['b'] for s in USED])) * 2
lv = {p: float(np.median([s1[s]['corner'][i]['clipped_mean'] for s in USED if useby[s]['clear']])) for i, p in enumerate(PLANE_NAMES)}
budget = dict(method='per frame, the scatter of 64 px blocks of the green planes against their level; straight line variance = a + b x level; for ONE colour plane', read_noise_dn=round(a ** 0.5, 1), gain_e_per_dn=round(1 / b, 4), read_noise_e=round(a ** 0.5 / b, 2),
              corner_level_clear_frames_dn={k: round(v, 1) for k, v in lv.items()}, sky_and_galaxy_shot_noise_dn={k: round((b * v) ** 0.5, 1) for k, v in lv.items()},
              reading='at 20 s and ISO 3200 the read noise (%.0f DN) is as large as the shot noise of the sky in green (%.0f DN) and larger than it in blue (%.0f) and red (%.0f): the frames are too short to be limited by the sky, most of all in red and blue' % (a ** 0.5, (b * lv['G1']) ** 0.5, (b * lv['B']) ** 0.5, (b * lv['R']) ** 0.5))
frames = []
for f in s1l['frames']:
    s = f['stamp']; o = tr[s]; qq = q[s]; u = useby.get(s)
    d = dict(file=f['name'], shutter_pressed_utc=f['t'], exposure_s=f['exposure_s'], iso=f['iso'], altitude_deg=round(f['alt_deg'], 1) if f.get('alt_deg') else None, arw_sha256=f.get('arw_sha256'),
             used=u is not None, rejected_because=rejby[s]['why'] if s in rejby else None,
             black_level=f['black'], corner_level_dn=dict(zip(PLANE_NAMES, [round(c['clipped_mean'], 2) for c in f['corner']])), corner_level_green_dn=round(f['corner_green'], 2), corner_noise_dn=dict(zip(PLANE_NAMES, [round(c['clipped_std'], 2) for c in f['corner']])),
             transparency=round(qq['flux_rel'], 4) if qq.get('flux_rel') is not None else None, stars_detected=qq['stars_detected'], half_flux_diameter_arcsec=round(qq['hfd_arcsec'], 2) if qq.get('hfd_arcsec') else None, elongation_median=round(qq['elong_median'], 3) if qq.get('elong_median') and qq['elong_median'] < 100 else None,
             white_balance_as_shot=f['wb'], orientation_flag=f['flip'], transient_spikes_replaced=s2f[s]['transient_spikes_replaced'], nucleus_sensor_xy=[round(v) for v in f['nucleus_sensor_xy']] if (u is not None) else None,
             nucleus_max_dn_above_black=dict(zip(PLANE_NAMES, [round(v) for v in s2f[s]['nucleus_max_dn_above_black_repaired']])) if u is not None else None, pixels_at_ceiling_near_nucleus=int(sum(s2f[s]['ceiling_pixels_near_nucleus'])))
    if not o.get('failed'):
        d.update(registered=True, rotation_deg=round(o['rotation_deg'], 4), shift_at_frame_centre_px=[round(v, 2) for v in o['shift_at_centre_px']], transform_R=o['R'], transform_t=o['t'], registration=dict(stars_used=o['used'], weighted_rms_px=round(o['wrms_px'], 3), scale_if_left_free=round(o['similarity_scale'], 5)))
    else: d.update(registered=False)
    if u is not None:
        d.update(multiplied_by=round(u['scale'], 4), weight=round(u['weight'], 4), transparency_tilt_per_3000px=[round(v, 3) for v in u['tilt']], clear=u['clear'],
                 constant_subtracted_dn={v: dict(zip(PLANE_NAMES, [round(c, 2) for c in s8[v]['constants'][s]])) for v in 'ABC'}, slope_against_reference_green_blocks=round(s8['B']['slope_against_reference_green'][s], 4))
    frames.append(d)
def pointing(path):
    j = json.load(open(path)); p = j.get('pointing') or {}
    return j['camera'].get('exposure_s'), j['camera'].get('iso'), p.get('ra_deg'), p.get('dec_deg')
others = []
for f in s1l['all_in_window']:
    if f['exposure_s'] == EXPOSURE_S and f['iso'] == ISO: continue
    e, i, ra, de = pointing(f['path'][:-4] + '.json')
    others.append(dict(file=f['name'], exposure_s=e, iso=i, pointing_ra_dec_deg=[round(ra, 2), round(de, 2)], why='in the time window, but a 2 s ISO 6400 finder frame taken after the run with the telescope already on another field'))
for extra in sorted(glob.glob(os.path.join(STILLS, '20261004-0735*.json'))):
    if '.solve.' in extra: continue
    e, i, ra, de = pointing(extra)
    others.append(dict(file=os.path.basename(extra)[:-5] + '.ARW', exposure_s=e, iso=i, pointing_ra_dec_deg=[round(ra, 2), round(de, 2)], why='2 s ISO 6400 finder frame on M31 just before the run (before the window)'))
cloud_rej = [r for r in sel['rejected'] if r['why'].startswith('cloud')]; uneven = [r for r in sel['rejected'] if r['why'].startswith('thin cloud uneven')]
tools = dict(python=platform.python_version(), numpy=np.__version__, scipy=scipy.__version__, opencv=cv2.__version__, rawpy=rawpy.__version__, libraw=getattr(rawpy, 'libraw_version', None), tifffile=tifffile.__version__, pillow=PIL.__version__,
             note='deterministic array arithmetic only; nothing generative or learned')
def dec(v, k=10): return [round(float(x), 4) for x in v[::k]]
versions = {
 'A': dict(files=['m31-core-as-recorded.png', 'm31-core-as-recorded.jpg'], what='AS RECORDED: nothing done about the flat field. No vignetting profile, no dust left out. The glow in it is mostly the sky seen through the vignetting (brighter in the middle of the SENSOR), not the galaxy.'),
 'B': dict(files=['m31-core.png', 'm31-core.jpg', 'm31-core-dust.png', 'm31-core-dust.jpg', 'm31-core-linear.tif'], what='VIGNETTING PROFILE REMOVED (as asked): each colour plane divided by the smooth, radially symmetric, centred profile of its colour; sensor pixels under a known dust shadow left out of the average (not divided). The tilt of the flat and the shading at the top and bottom edge are still in it.'),
 'C': dict(files=['m31-core-cloudflat.png', 'm31-core-cloudflat.jpg', 'm31-core-cloudflat-starwhite.png', 'm31-core-cloudflat-starwhite.jpg', 'm31-core-dust-cloudflat.png', 'm31-core-dust-cloudflat.jpg', 'm31-core-cloudflat-linear.tif'],
           what='EXTRA, BEYOND WHAT WAS ASKED: each colour plane divided by the whole smooth cloud-glow flat of this run (radial part, tilt and edge shading, per plane); dust left out as in B, and the five shadow cores that could not be left out divided by their measured transmission. Offered because the flat could be measured tonight without assuming anything about the galaxy, and because it removes two things B leaves in. Use B if only the radial profile is to be trusted.'),
}
recipe = dict(
    what='M31 core (Andromeda galaxy, the dust lanes round the nucleus), %d x 20 s at ISO 3200 (%.1f minutes; worth %.1f minutes of clear sky), Sony a6000 on a Celestron 8SE at f/10, stacked from RAW colour planes' % (n_used, n_used * 20 / 60, wsum * 20 / 60),
    made_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(timespec='seconds'), tools=tools,
    which_picture_is_which=versions,
    source=dict(folder=STILLS, window_utc=[T0, T1], frames_found_at_20s_iso3200=len(s1l['frames']), frames_used=n_used, frames_rejected=len(sel['rejected']), rejected_for_cloud=len(cloud_rej), rejected_for_uneven_thin_cloud=len(uneven),
                total_exposure_s=n_used * 20, clear_frames_among_used=sum(u['clear'] for u in sel['used']), thin_cloud_frames_among_used=sum(not u['clear'] for u in sel['used']), summed_weights=round(wsum, 2), clear_sky_equivalent_exposure_s=round(wsum * 20),
                left_out=others, originals='read in place, not modified'),
    what_the_bright_sky_frames_are=dict(
        finding='CLOUD, not a lamp. In every frame where the level in the corner is up, the stars are down: at a corner level of 1.2 x the clear level the stars keep 75 to 80% of their light, at 2 x about 30%, at 3 x about 10%, at 4 x and more under 5%. A lamp near the telescope would add light and leave the stars alone.',
        corner_region='plane px rows 20..320, cols 20..320 = the top-left 600 x 600 sensor px; 3-sigma clipped mean of each colour plane, black subtracted', clear_level_green_dn=round(sel['corner_green_clear_median'], 1),
        note_on_the_level_given_in_the_task='the task quoted about 124 DN when dark: that is a median over the whole half-size frame; in this darker corner the clear level is %.0f DN' % sel['corner_green_clear_median'],
        frames_by_transparency={k: int(sum(1 for o in Q['quality'] if (o['flux_rel'] or 0) >= lo and (o['flux_rel'] or 0) < hi)) for k, lo, hi in (('0.97_and_up', 0.97, 9), ('0.90_to_0.97', 0.90, 0.97), ('0.80_to_0.90', 0.80, 0.90), ('0.60_to_0.80', 0.60, 0.80), ('0.30_to_0.60', 0.30, 0.60), ('below_0.30_or_not_measurable', -1, 0.30))}),
    selection=dict(rule='a frame is used if the measured transparency (star brightness over the clear frames, median of up to %d stars) is at least %.2f, AND the transparency is even across the field (straight-line fit of star brightness against position: less than %.0f%% change per 3000 px), AND stars no wider than %.2f x the clear median, AND median elongation <= %.2f, AND registration rms <= %.1f px' % (Q['quality_stars'], sel['limits']['transparency_min'], 100 * sel['limits']['tilt_max'], sel['limits']['hfd_max_rel'], sel['limits']['elongation_max'], sel['limits']['registration_wrms_max_px']),
                   limits=sel['limits'], in_terms_of_sky_level='the highest corner level among the used frames is %.0f DN green = %.2f x the clear level (%.0f DN); every frame above 1.35 x is out. The test itself is the star brightness, not the level.' % (sel['corner_green_max_used'], sel['corner_green_max_used'] / sel['corner_green_clear_median'], sel['corner_green_clear_median']),
                   weights='used frames are multiplied by 1 / transparency and averaged with weight (transparency / noise)^2, noise = the frame\'s measured corner noise over the clear median: the inverse variance of the scaled frame in the faint parts. Clear frames 0.87 to 1.05, thin-cloud frames 0.61 to 0.80.',
                   why_weights_and_not_clear_frames_only=N['weighted_against_clear_only'], half_flux_diameter_clear_median_arcsec=round(sel['hfd_clear_median_arcsec'], 2)),
    frames=frames,
    motion=dict(N['motion'], note='the task expected about 0.08 degrees per minute and 5.5 degrees in all; measured: %.3f degrees over the run (%.4f per minute at the start, %.4f at the end). Similarity transform with the scale held at 1; with the scale left free it came out %s.' % (N['motion']['all_registered_frames']['rotation_total_deg'], N['motion']['rotation_rate_first_ten_minutes_deg_per_minute'], N['motion']['rotation_rate_last_quarter_hour_deg_per_minute'], N['motion']['scale_if_left_free_range'])),
    steps=[
        dict(step='read', detail='rawpy raw_image_visible (sensor orientation, 6024 x 4024, RGGB), black level 512 subtracted; four colour planes R, G1, G2, B kept apart at 3012 x 2012, no demosaic. The camera\'s orientation flag (5 or 3 in these frames) is ignored.'),
        dict(step='hot pixels', detail='fixed: per-plane median, without registration, of the %d frames whose corner level is below 1.15 x the floor (each minus its corner level); a pixel is hot if it stands above the 5x5 median of that by more than max(6 sigma, 25%% of the level) AND above its highest neighbour by half that (so a star that barely moves on the sensor is not taken for one). Single-frame spikes: above the 3x3 median by more than 8 sigma + 50%% of the level, sigma scaled with the square root of the level. Both replaced by the 3x3 median of the same plane before anything else.' % len(s2['frames_in_hot_median']),
             fixed_hot_pixels={h['plane']: h['fixed_hot'] for h in s2['hot']}, fraction_of_plane={h['plane']: round(h['frac'], 5) for h in s2['hot']}),
        dict(step='stars', detail='green planes averaged (half-size grid). The smooth light (galaxy and sky) is taken off first: plane shrunk 8x, 5x5 median, Gaussian sigma 2, grown back. Detection on the remainder blurred with sigma 2.5, in units of the local noise (variance = a + b x level fitted to the frame\'s own 64 px blocks), 6 sigma, connected blobs of 8 px or more. Gaussian-windowed centroid (sigma 5 plane px); 28 px (sensor) aperture, ring 38 to 54 px for the local level.'),
        dict(step='register', detail='reference frame %s (clear, near the middle of the turn). Stars more than %d px from the nucleus, not within 1500 DN of the ceiling, no neighbour within 40 px, at least %d DN in the reference. The frames are walked outward in time from the reference, each starting from its neighbour\'s solution; match radius 30, 12, 4 px; weighted least-squares rotation + shift (similarity with the scale held at 1), weights 1/(0.25^2 + (14000/flux)^2), 3.5-sigma rejection.' % (REF_STAMP, CORE_RADIUS, int(T4['minflux'])),
             stars_in_reference=len(T4['reference_stars_xy']), stars_used_range_used_frames=[min(tr[s]['used'] for s in USED if s != REF_STAMP), max(tr[s]['used'] for s in USED if s != REF_STAMP)], weighted_rms_px_range_used_frames=[round(min(tr[s]['wrms_px'] for s in USED if s != REF_STAMP), 3), round(max(tr[s]['wrms_px'] for s in USED), 3)],
             frames_not_registered=[o['stamp'] for o in T4['transforms'] if o.get('failed')]),
        dict(step='transparency', detail='%d stars (more than %d px from the nucleus, unsaturated, isolated, at least %d DN): each star\'s aperture flux over that star\'s median flux in the clear frames; the frame\'s transparency is the median over the stars.' % (Q['quality_stars'], CORE_RADIUS, int(Q['qflux']))),
        dict(step='flat field: what was measured', detail='No flat frames exist. Nothing was built from these frames by assuming the sky or the galaxy is flat. Instead the cloud gave a flat: a clouded frame minus (its measured transparency x the nearest clear frame) is the cloud\'s own glow, which lights the aperture evenly, seen through the optics; the galaxy and the sky cancel. Median over %d clouded frames (transparency <= 0.40, glow %d to %d DN in green), in sensor coordinates. Within 400 px of the nucleus the galaxy does not cancel (it shifts between the two frames) and the flat is not used.' % (len(vig['frames']), round(min(f['glow_green_dn'] for f in vig['frames'])), round(max(f['glow_green_dn'] for f in vig['frames']))),
             cloud_frames=vig['frames']),
        dict(step='vignetting profile (versions B and C)', detail='smooth, radially symmetric, centred on the sensor centre, one per colour (blue is less vignetted than green and red, measurably): ring medians (150 px rings) of 16 px block medians of the cloud-glow flat, a fitted linear tilt divided out first so that it cannot bias the rings, smoothing spline, V(0) = 1, never rising outward. Version B divides each plane by V of its colour and by nothing else.',
             centre_sensor_px=vig['centre_sensor_px'], r_px=dec(vig['r_px']), V_red=dec(vig['V']['R']), V_green=dec(vig['V']['G']), V_blue=dec(vig['V']['B']), ring_measurements=vig['rings'],
             independent_check_m15_sky_flat=dict(what='the sky of the M15 run (23 x 15 s ISO 1600, 0720 to 0733 UTC, empty sky outside 8.1 arcmin of the cluster), same method, over this profile; 1.000 = same shape (normalised at 900 to 1500 px)', rings=vig['check_against_m15_sky_flat'],
                                                  reading='the two flats agree within 1.5% in green, 2.2% in blue and 2.8% in red (the M15 red sky is only 20 DN) out to the corner; the M15 flat is a little lower in the outer rings, as a black level 1 to 3 DN off would make it',
                                                  polynomial_fits_m15_ngc7662_cloud={k: dict(sky_dn=round(v['sky_dn'], 1), V_at_r=v['V_at_r'], tilt_per_3000px=[round(t, 4) for t in v['gradient_per_3000px']]) for k, v in vfit.items()}),
             check_inside_the_m31_frames=dict(what='stack of the first third of the used frames minus stack of the last third (the field sits about 170 px away and is turned 2.3 degrees between them), green, 256 px block medians, blocks with under 400 DN', A_as_recorded=chk['A'], B_profile_removed=chk['B'], C_whole_flat=chk['C'],
                                              reading='as recorded the two thirds differ by 2.8 DN rms (-5.6 to +5.4); with the profile removed 0.9 DN rms. What is left is a straight slope: the sky\'s own gradient changed during the hour by about 1.4 DN in x and 1.9 DN in y per 3000 px. No constant per frame can take that out; it is in every version at the level of +-2 DN across the field.')),
        dict(step='what the radial profile leaves in (version B)', detail='the cloud-glow flat also shows (1) a tilt: about +4% per 3000 px in x and -3% in y (right and top brighter); the M15 sky flat shows +2.6% and -1.1 to -2.1%, the same sign; (2) strips about 450 px deep at the top and bottom edge that are 1 to 4% dark, differently for the two row pairs of the colour cell (top: R and G1 3 to 4%, G2 and B about 1.3%). On a sky of about 125 DN these are +-5 DN and -3 to -5 DN: as large as the galaxy\'s outer glow. Version B leaves them in, as asked. Version C divides them out.',
             tilt_per_3000px=vig['tilt_not_applied_per_3000px'], flat2d=flat2d),
        dict(step='dust shadows', detail='map: the green cloud-glow flat, Gaussian sigma 2.5 plane px, over the smooth model; marked where below %.3f (or a sigma-4 copy below %.3f), blobs of at least %d plane px, grown by %d px: %d patches, %.1f%% of the sensor. Near the nucleus, where this flat is blind, the M15 run\'s dust map marks %s. In versions B and C the marked sensor pixels are LEFT OUT of the average (nothing is divided). The field moves about 150 to 250 px over the sensor during the run, so most places still have clean frames; where fewer than %d are left, the combine with the dust left in is blended in (fully below %d).' % (dust['ratio_threshold'], dust['ratio_threshold_wide'], dust['min_blob_plane_px'], dust['grow_plane_px'], dust['patches'], 100 * dust['marked_fraction_of_sensor'], dust['blind_zone'].split(': ')[-1], BLEND_HI, BLEND_LO),
             measured={k: v for k, v in dust.items() if k != 'all_patches'}, what_is_left=dustmap,
             map_file='m31-core-sensor-dust-map.png: same geometry as m31-core.png; white = no sensor shadow expected, darker = deeper (black = 20% or more of the light lost)'),
        dict(step='scale', detail='each used frame multiplied by 1 / its transparency (0.82 to 1.02), so that clear and thin-cloud frames agree. Check: slope of the frame against the reference frame over 64 px block medians of green (levels up to 3000 DN) is %.3f to %.3f.' % (min(v for k, v in s8['B']['slope_against_reference_green'].items() if k != REF_STAMP), max(v for k, v in s8['B']['slope_against_reference_green'].items() if k != REF_STAMP))),
        dict(step='resample', detail='each plane of each frame mapped straight onto the reference frame\'s sensor grid (rotation + shift + the plane\'s own place in the 2x2 colour cell) with OpenCV remap, Lanczos-4. No demosaic.'),
        dict(step='one constant per frame and colour plane', detail='chosen so that the frame matches the reference frame in the darkest quarter of the reference (3-sigma clipped mean of the difference, on the half-size grid). It takes out the sky level, the cloud\'s glow and the black level, which steps by 4 DN from frame to frame and plane to plane in this camera. No surface is fitted or subtracted anywhere.'),
        dict(step='combine', detail='per pixel and plane: values further than 3 sigma from the median are dropped (sigma = 1.4826 x MAD across the frames, floor 0.4 x the single-frame noise, widened by each frame\'s noise factor), then again 3 sigma about the weighted mean of the survivors, then the weighted mean.', kappa=s8['B']['kappa'], per_plane=dict(A=s8['A']['planes'], B=s8['B']['planes'], C=s8['C']['planes'])),
        dict(step='crop', detail='the largest rectangle in which every pixel is covered by at least 80%% of the used frames (%d of %d): sensor px x %d..%d, y %d..%d = %d x %d px = %.1f x %.1f arcmin. m31-core-coverage.tif has the number of frames actually used at every pixel of it (green plane, version B, after the dust and the clip).' % (int(np.ceil(0.8 * n_used)), n_used, x0, x1, y0, y1, x1 - x0, y1 - y0, (x1 - x0) * SCALE / 60, (y1 - y0) * SCALE / 60)),
        dict(step='zero level', detail='THE ABSOLUTE ZERO IS UNKNOWN: the galaxy fills the frame and the sky under it cannot be measured. One constant per colour plane is subtracted so that the darkest part of the field sits at zero: the median of each plane over the pixels where the smoothed green is below its 1st percentile, tracks of dust shadows and the strips 450 px from the top and bottom of the sensor left out; the same pixels for all planes, so that region is neutral by construction. The galaxy is not zero there. Everything in the pictures is brightness ABOVE that region.', per_version=s10['zero']),
        dict(step='colour', detail='G = mean of G1 and G2; R x %.4f and B x %.4f: the camera\'s as-shot white balance from the RAW (median over the used frames; the camera changed it from frame to frame, %s). No colour matrix, no saturation change. The star-white extra uses R x %.4f and B x %.4f instead: the multipliers that make the mean of %d unsaturated field stars of this stack neutral (the bulge is not used as a reference).' % (s10['wb']['as_shot']['R'], s10['wb']['as_shot']['B'], 'R 2744 to 2868, B 1752 to 1812 over the used frames', s10['wb']['star_neutral']['R'], s10['wb']['star_neutral']['B'], star['stars']),
             as_shot_multipliers=s10['wb']['as_shot'], star_neutral_multipliers=s10['wb']['star_neutral'], field_stars={k: v for k, v in star.items() if k != 'list'}),
        dict(step='stretch', detail='arcsinh on brightness, colour ratios kept, then the sRGB transfer curve, 8 bit. Brightness L = green. Colour = the ratios R:G:B of a copy blurred with a Gaussian of sigma %.0f sensor px (smaller than a star; red and blue are 2 to 3 times noisier than green and this keeps their grain out; brightness is not blurred). f = asinh((min(L, white) + pedestal) / soft) / asinh((white + pedestal) / soft); out = ratio x f; clip 0..1. The same numbers for every picture.' % s10['chroma_sigma_sensor_px'], **s10['stretch'], chroma_sigma_sensor_px=s10['chroma_sigma_sensor_px']),
    ],
    numbers=dict(noise=N['noise'], noise_budget_one_frame=budget, stars_in_the_stack=N['stars_in_the_stack'], raw_clipping=N['raw_clipping'], glow_block_medians=dict(what='384 px block medians, DN above the zero region, as-shot white balance; rows top to bottom, columns left to right', **N['glow_block_medians'])),
    sharpening=dict(delivered=False, tried='on the dust-lane crop, green: Richardson-Lucy 5 and 10 rounds (blur = median of %d isolated unsaturated stars of this stack, checked on %d others) and an unsharp mask (amount 0.6, sigma 4 px)' % (sharp['blur_stars'], sharp['check_stars']), results=sharp['results'],
                    why_not='Richardson-Lucy draws a dark ring round every star: 1.5% of the star\'s peak after 5 rounds, 1.9% after 10, which is 27 and 38 DN (median) below a galaxy that is 10 to 40 DN bright there. The unsharp mask digs 6.5 DN (median) and raises the grain by 60%. The lanes are limited by noise, not by blur.'),
    outputs={
        'm31-core.png / .jpg': dict(version='B', area='the whole well-covered field', scale='half scale: 2 x 2 block mean of the sensor grid, 0.776 arcsec per pixel. Stars are 4.1 arcsec (10.5 sensor px) wide, so half scale shows everything the data resolves and halves the grain.', **s10['outputs']['m31-core']),
        'm31-core-as-recorded.png / .jpg': dict(version='A', scale='half scale', **s10['outputs']['m31-core-as-recorded']),
        'm31-core-dust.png / .jpg': dict(version='B', crop_sensor_px=dict(x0=s10['dust_crop'][0], y0=s10['dust_crop'][1], x1=s10['dust_crop'][2], y1=s10['dust_crop'][3]), scale='the sensor\'s own: one picture pixel is one sensor pixel, 0.388 arcsec; 15.5 x 10.3 arcmin', **s10['outputs']['m31-core-dust']),
        'm31-core-linear.tif': dict(version='B', what='linear, 32-bit float RGB, as-shot white balance applied, zero level subtracted, not stretched', units='DN of the 14-bit RAW scale per 20 s frame under a clear sky (green as measured; R and B multiplied by the white balance)', size_px=[x1 - x0, y1 - y0], pixel_scale_arcsec=SCALE, origin='pixel (0,0) is sensor pixel (%d,%d) of the reference frame %s' % (x0, y0, REF_STAMP), compression='zlib, lossless'),
        'm31-core-coverage.tif': dict(what='8-bit: the number of frames used at each pixel (green plane, version B), same grid as the linear file; %d = all' % n_used),
        'm31-core-sensor-dust-map.png': dict(what='diagnostic, half scale, same geometry as m31-core.png: where a sensor dust shadow is still in the picture and how deep (white = none, black = 20% of the light or more)'),
        'm31-core-cloudflat.png / .jpg (extra)': dict(version='C', scale='half scale', **s10['outputs']['m31-core-cloudflat']),
        'm31-core-cloudflat-starwhite.png / .jpg (extra)': dict(version='C', colour='star-white multipliers', **s10['outputs']['m31-core-cloudflat-starwhite']),
        'm31-core-dust-cloudflat.png / .jpg (extra)': dict(version='C', scale='the sensor\'s own', **s10['outputs']['m31-core-dust-cloudflat']),
        'm31-core-cloudflat-linear.tif (extra)': dict(version='C', what='as m31-core-linear.tif'),
        'jpg': 'quality 92, 4:4:4, no metadata', 'png': '8-bit RGB, no metadata', 'marks': 'nothing is drawn on any picture',
    },
    orientation='sensor orientation of the RAW (as rawpy raw_image_visible), on the grid of the reference frame; not rotated to north and not plate solved here',
    do_not_trust=[
        'The zero. The galaxy fills the frame; the pictures show brightness above the darkest clean part of the field, where the galaxy is not zero. How far the glow really reaches cannot be read off them.',
        'The outer glow in version B (m31-core): the tilt of the flat (about +-5 DN across the frame) and the edge shading (3 to 5 DN in the top and bottom 450 px) are still in it. They make the dark band along the top edge and tint the outer glow brown (red over green 1.3 to 1.5 there against 1.07 in the bulge). In version C, with the whole cloud-glow flat removed, the glow has the colour of the bulge everywhere (1.05 to 1.13) and is brighter to the left than to the right. That agreement is why C is believed; but C rests on the cloud\'s glow being even across 0.65 degrees, and the only independent flat (the M15 sky) confirms the tilt in sign and rough size, not to the percent.',
        'Sky gradients. The sky\'s own slope across the field changed during the hour by about 2 DN per 3000 px; one constant per frame cannot remove that. A smooth +-2 DN is in every version and cannot be told from the galaxy.',
        'The hue of the faintest glow in any version: 1 DN of red is 2.75 DN after white balance, and the glow in the outer field is 5 to 20 DN.',
        'One black smudge near the top edge, right of centre (whole-field picture px about 1872, 83; sensor px 3851, 275): the hair on the sensor. It is too long for the field\'s motion to clear, it moved during the hour, and it is still there in every version (smaller in C). Not sky.',
        'Four faint smooth smudges (6 to 8% deep before, listed in the dust step with their places): sensor dust that could not be left out. Gone in C. The map m31-core-sensor-dust-map.png shows all five.',
        'Faint dust rings shallower than about 1.4% are not marked; smeared along the field\'s track they are under 1 DN. Anything smooth, dark, 100 to 300 px long and running along the direction of the drift is suspect. The other way round: a sensor shadow is smeared over at least 150 px, so a dark lane narrower than that is on the sky.',
        'Within 400 px of the nucleus the cloud-glow flat is blind; the dust there is known only from the noisier M15 map.',
        'The 11 thin-cloud frames: scaled by their transparency; cloud is never perfectly even. Against the clear frames alone the stack differs by 0.3 DN rms (at most 0.65 DN) on scales of 256 px.',
        'Grain: red and blue are 2 to 3 times noisier than green after white balance. Colour is taken from a copy blurred by 4 px; colour detail finer than a star is not shown. In the outer field the galaxy is 5 to 20 DN and one sensor pixel has 7 DN of noise in green.',
        'Stars: 4.1 arcsec wide and not round (elongation 1.23, the optics). The cores of the few brightest stars hit the sensor ceiling and are flat-topped; the nucleus does not (53% of the ceiling at most).',
        'The corners: fewer frames (see the coverage file) and the strongest vignetting correction (divided by 0.72 to 0.76 at the very corner), so the grain is 1.4 times coarser there.',
    ],
    what_would_help_most=[
        'A clear sky: 71 of 109 frames went to cloud. The same hour without it is three times the exposure.',
        'The dawn flats: they settle the tilt, the edge shading and the dust at once, and with them the outer glow and its colour. Until then version C stands in for them.',
        'Longer frames once the mount tracks well enough: at 20 s the read noise equals the sky\'s noise in green and exceeds it in red and blue. 60 s frames would be sky-limited in all three; at today\'s drift (about 0.06 arcsec per second along its path) a 60 s frame trails by a star\'s width, so polar alignment or guiding comes first.',
        'Moving the field on purpose between frames by more than 300 px (larger than the largest dust shadow): then every shadow can be left out everywhere.',
        'Empty sky for the zero: a few frames a degree or two off the galaxy, taken in between, would give the sky level and the true extent of the glow.',
    ],
    scripts='scripts/ beside this file, run in this order: common.py, step1_levels.py, step2_hot.py, step3_stars.py, step4_register.py, step5_quality.py, vig1_skyflats.py, vig3_cloudflat.py, vig2_fit.py (polynomial fits to the M15 and NGC 7662 sky flats and to the cloud-glow flat, as checks), step6_flat.py, step6c_flat2d.py, step7_select.py, step8_stack.py A / B / C, final.py, check_flat.py, starcolour.py, step9_dustmap.py, step10_deliver.py, try_sharpen.py, step11_recipe.py; render.py, measure.py, decon.py are helpers. Adapted from ../m15/scripts.',
)
json.dump(recipe, open(os.path.join(DEST, 'm31-core-recipe.json'), 'w'), indent=1)
print('recipe written:', os.path.join(DEST, 'm31-core-recipe.json'), os.path.getsize(os.path.join(DEST, 'm31-core-recipe.json')), 'bytes')
print(recipe['what']); print(json.dumps(recipe['source'] | {'left_out': recipe['source']['left_out']}, indent=0)[:1500]); print(json.dumps(recipe['what_the_bright_sky_frames_are']['frames_by_transparency'])); print(json.dumps(budget, indent=0))
