defmodule Controller.Endpoint do
  use Phoenix.Endpoint, otp_app: :controller

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_controller_key",
    signing_salt: "mYNmjMNd",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  # LiveView's JS straight from the deps — no bundler on this project.
  plug Plug.Static, at: "/vendor/phoenix", from: {:phoenix, "priv/static"}, gzip: false
  plug Plug.Static, at: "/vendor/live_view", from: {:phoenix_live_view, "priv/static"}, gzip: false
  # data-confirm ("Zero both axes?") lives in phoenix_html.js, not in LiveView's bundle
  plug Plug.Static, at: "/vendor/phoenix_html", from: {:phoenix_html, "priv/static"}, gzip: false

  plug Plug.Static,
    at: "/",
    from: :controller,
    gzip: not code_reloading?,
    # No bundler and no digests: make browsers revalidate assets every load.
    cache_control_for_etags: "no-cache",
    only: Controller.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug Controller.Router
end
